version: '3'

services:
  user-api:
    build:
      context: ./
      dockerfile: user/Dockerfile
    image: share-report/user
    container_name: user
    ports:
    - "50051:50051"
  user-db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
    - "53306:3306"
    volumes:
      - "./user/mysql-data/:/docker-entrypoint-initdb.d/"