name: Hello World

on: 
  push:
    branches:
      - main

jobs:
  say_hello_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!(1)"
  say_hello_2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!(2)"
